import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
const hash = createHash("sha256");
hash.update(process.env.VERCEL_GIT_COMMIT_SHA || process.env.GITHUB_SHA || "local");
for (const path of [
  "public/sw.js",
  "app/manifest.ts",
  "public/brand/app-icon-192.png",
  "public/brand/app-icon-512.png",
  "public/brand/app-icon-maskable.png",
  "public/brand/apple-touch-icon.png",
  "public/offline.html",
  "public/offline.js",
  "public/offline.css",
  "public/data/places.json",
  "public/data/cities.json",
])
  hash.update(await readFile(path));
const release = hash.digest("hex").slice(0, 16);
await writeFile(
  "public/pwa-release.js",
  `/* Generated by the production build. */\nself.CITYLIT_PWA_RELEASE = ${JSON.stringify(release)};\n`,
);
console.log(`PWA offline release: ${release}`);
